### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by steelcowboy** [redomar/JavaGame#8]
I want to use this game and re-engineer it for a school project (which is allowed for our class); however, since there is no license I am unsure what restrictions apply and where credit is expected :) 

You can find info on some various licenses here: http://choosealicense.com/ 

Thanks!

**Comment by redomar** [comment]
Fixed issue #8
There was no license previously

### License TL;DR

#### You must:
* Disclose Source and not hide it
* Include a copy of the license notice with the code (Don't delete the LICENSE file)
* State changes you made to the original file

#### You are allowed to:
* For commercial use
* Distribution
* Modification (Must state)
* Patent grant (Must had contributed)
* Private Use (e.g school project)

#### You aren't allowed to:
* Hold liable, this software comes with no warranty and you must not hold me liable for any damages caused by the software.
* Sub-licensing.
